name: "Cast to Farcaster"
description: "Cast to Farcaster"
inputs:
    message:
        description: "Message to cast"
        required: true
    signer-uuid:
        description: "Signer UUID required to cast on behalf of a profile"
        required: true
    neynar-api-key:
        description: "Neynar API Key to cast"
        required: true
    embeds:
        description: "Comma-separated list of embeds in the cast (can be url or cast ids)"
    channel-id:
        description: "Channel Id of the channel to cast in (must have access to cast)"
runs:
    using: "node20"
    main: "dist/index.js"
